E-Mechanik Web/Models/Service.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace E_Mechanik_Web.Models
{
    public class Service : IEntity
    {
        [Required]
        [Display(Name = "Nazwa usługi")]
        public string Name { get; set; }
        [Display(Name = "Odległość")]
        public string Distance { get; set; }
        [Display(Name = "Login mechanika")]
        public string MechanicName { get; set; }
        public virtual MechanicProfiles mechanicProfile { get; set; }
        public int AvailableServiceCategoryId { get; set; }
    }
}

E-Mechanik Web/Controllers/MessagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using E_Mechanik_Web.Models;

namespace E_Mechanik_Web.Controllers
{
    [Authorize]
    public class MessagesController : BaseController
    {
        // GET: Messages
        [Authorize]
        public ActionResult Index()
        {
            var message = _db.Messages.Where(c=>c.ReceiverName == User.Identity.Name);
            if (message != null)
            {
                return View(message);
            }
            return HttpNotFound();
        }

        // GET: Messages/Details/5
        [Authorize]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Message message = _db.Messages.Find(id);
            if (message == null)
            {
                return HttpNotFound();
            }
            return View(message);
        }
        [Authorize]
        public ActionResult DirectMessage(string to)
        {
            Message message = new Message { ReceiverName = to };
            return View("Create", message);
        }
        // GET: Messages/Create
        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReceiverName,Subject,Text")] Message message)
        {
            if (ModelState.IsValid)
            {
                var x = _db.Users.Where(c => c.Email == message.ReceiverName).Select(c => c.Email).FirstOrDefault() ;
                if (x!=null)
                {
                    message.SendTime = DateTime.Now.ToString("mm:hh | dd.MM.yyyy");
                    message.SenderName = User.Identity.Name;
                    _db.Messages.Add(message);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "Użytkownik, do którego chcesz wysłać wiadomość nie istnieje!";
                    return View();
                }
               
            }

            return View(message);
        }

        [Authorize]
        // POST: Messages/Delete/5
        public ActionResult Delete(int id)
        {
            Message message = _db.Messages.Find(id);
            if (message!=null)
            {
                if (message.ReceiverName==User.Identity.Name)
                {
                    _db.Messages.Remove(message);
                    _db.SaveChanges();
                    return RedirectToAction("index");
                }
            }

            return HttpNotFound();


        }
        [Authorize]
        public ActionResult Reply(int id)
        {
            Message message = _db.Messages.Where(c => c.Id == id).FirstOrDefault();
            string z = message.SenderName;
            message.SenderName = message.ReceiverName;
            message.ReceiverName = z;
            message.Subject = "Re: " + message.Subject;
            message.Text = "Od: " + message.ReceiverName + ": \"" + message.Text + "\"\n\n"; 
            return View(message);
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Reply([Bind(Include = "ReceiverName,Subject,Text")] Message message)
        {
            if (ModelState.IsValid)
            {
                var x = _db.Users.Where(c => c.Email == message.ReceiverName).Select(c => c.Email).FirstOrDefault();
                if (x != null)
                {
                    message.SendTime = DateTime.Now.ToString("mm:hh | dd.MM.yyyy");
                    message.SenderName = User.Identity.Name;
                    _db.Messages.Add(message);
                    _db.SaveChanges();
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "Użytkownik, do którego chcesz wysłać wiadomość nie istnieje!";
                    return View();
                }

            }

            return View(message);
        }

    }
}

E-Mechanik Web/Controllers/ServicesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Web.Mvc;
using System.Web.Services;
using E_Mechanik_Web.Models;
using E_Mechanik_Web.ViewModels;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace E_Mechanik_Web.Controllers
{
    public class ServicesController : BaseController
    {
        // GET: Services
        public ActionResult Index(int? categoryId = null)
        {
            IEnumerable<Service> services = _db.Services;
            List<Service> list = services.ToList();
            var list2 = new List<string>();
            foreach (var item in services)
            {
                if (list2.Contains(item.Name))
                {
                    list.Remove(item);
                }
                else
                {
                    list2.Add(item.Name);
                }
            }
            return View(list);
        }

        // GET: Services/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = _db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        [HttpGet]
        public ActionResult GetServices(string service)
        {
            IEnumerable<SelectListItem> services;
            int categoryId = Int32.Parse(service);
            if (_db.AvailableServices.Any(c => c.AvailableServiceCategoryId == categoryId))
            {
                services = _db.AvailableServices.Where(p => p.AvailableServiceCategoryId == categoryId).Select(n => new SelectListItem { Value = n.Id.ToString(), Text = n.Name });
                return Json(services, JsonRequestBehavior.AllowGet);
            }
            return Json("Przyklad", JsonRequestBehavior.AllowGet);
        }

        [Authorize(Roles = "Mechanic")]
        // GET: Services/Create
        public ActionResult Create()
        {
            MechanicProfiles k = _db.MechanicProfiles.Where(c => c.MechanicName == this.User.Identity.Name).FirstOrDefault();
            if (k!=null)
            {
                if (k.MechanicName == null || k.CompanyName == null || k.City == null || k.Address == null)
                {
                    return RedirectToAction("FillMechanicProfile", "Account");
                }
                var model = new CreateServiceViewModel();
                model.Categories = _db.AvailableServiceCategories.Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() });
                model.Services = _db.AvailableServices.Select(c => new SelectListItem { Text = c.Name, Value = c.Id.ToString() });
                return View(model);
            }
            else
            {
                return RedirectToAction("FillMechanicProfile", "Account");
            }
           
        }

        // POST: Services/Create
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Mechanic")]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name,Price,ExecutionTime,AvailableServiceCategoryId")] Service service)
        {
            if (ModelState.IsValid)
            {
                var x = service.AvailableServiceCategoryId;
                var Name = this.HttpContext.User.Identity.Name;
                service.MechanicName = Name;
                service.mechanicProfile = _db.MechanicProfiles.Where(c => c.MechanicName == service.MechanicName).FirstOrDefault();
                _db.Services.Add(service);
                _db.SaveChanges();
                return RedirectToAction("MyServices");
            }

            return View(service);
        }



        [Authorize(Roles = "Mechanic")]
        // GET: Services/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = _db.Services.Find(id);
            if (service == null)
            {
                return HttpNotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // Aby zapewnić ochronę przed atakami polegającymi na przesyłaniu dodatkowych danych, włącz określone właściwości, z którymi chcesz utworzyć powiązania.
        // Aby uzyskać więcej szczegółów, zobacz https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [Authorize(Roles = "Mechanic")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,ExecutionTime,MechanicId,ServiceId")] Service service)
        {
            if (ModelState.IsValid)
            {
                _db.Entry(service).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("MyServices");
            }
            return View(service);
        }

        [Authorize(Roles = "Mechanic")]
        // GET: Services/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Service service = _db.Services.Find(id);
           
            if (service == null)
            {
                return HttpNotFound();
            }
            if (service.MechanicName == User.Identity.Name)
            {
                return View(service);
            }
            else
            {
                return HttpNotFound();
            }
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Service service = _db.Services.Find(id);
            _db.Services.Remove(service);
            _db.SaveChanges();
            return RedirectToAction("MyServices");
        }

        public ActionResult GetServicesByName(string name)
        {
            IEnumerable<Service> services = _db.Services.Where(c => c.Name == name);
        
            return View(services);
        }
        [Authorize(Roles ="Mechanic")]
        public ActionResult MyServices()
        {
            IEnumerable<Service> services = _db.Services.Where(c => c.MechanicName == User.Identity.Name);
            return View(services);
        }
    }
}

E-Mechanik Web/Views/Services/Create.cshtml
@model E_Mechanik_Web.ViewModels.CreateServiceViewModel
@{
    /**/

    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Service</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.AvailableServiceCategoryId, "Kategoria usługi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.AvailableServiceCategoryId, new SelectList(Model.Categories, "Value", "Text"), htmlAttributes: new { @class = "form-control", @id = "Category" })
                @Html.ValidationMessageFor(model => model.AvailableServiceCategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(x => x.Name, "Nazwa usługi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-5">
                @Html.DropDownListFor(x => x.Name, new SelectList(Model.Services, "Text", "Text"), htmlAttributes: new { @class = "form-control", @id = "Service" })
                @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        $('#Category').change(function funkcja() {
                var selectedCategory = $("#Category").val();
                var serviceSelect = $('#Service');
            serviceSelect.empty();

            if (selectedCategory != null && selectedCategory != '') {
                $.getJSON('@Url.Action("GetServices", "Services")', { service: selectedCategory }, function (services) {
                     if (services != null && !jQuery.isEmptyObject(services))
                        {
                         serviceSelect.append($('<option/>', {
                                value: null,
                                text: ""
                            }));
                         $.each(services, function (index, service) {
                             serviceSelect.append($('<option/>', {
                                    value: service.Text,
                                    text: service.Text
                                }));
                            });
                        };
                    });
                }
            });
    </script>
}

E-Mechanik Web/Views/Services/Delete.cshtml
@model E_Mechanik_Web.Models.Service

<hr style="height:1px; background-color:rgba(0,0,0,0.5);" />
<div class="CustomHeader" style="height:85px">
    <h2>Usuwanie usługi</h2>
</div>

<div class="allServicesFromCategoryBox">

    <div class="singleServiceBox" style="padding-left:15px; margin-top:0px" ;>
        <h3 class="LinkColor" style="margin-top:0px;">Czy na pewno chcesz usunąć @Model.Name ze swoich usług?</h3>
    </div>
    <div style="height:60px; background-color: rgba(0,0,0,0.65); margin-top:1px; border:1px solid rgba(0,0,0,0.5); border-radius:5px">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions" style="margin-left:360px; margin-top:10px;">
                @Html.ActionLink("Wróć do listy", "MyServices", null, new { @class = "btn btn-default", style = "border:2px solid rgba(0,0,0,0.2);" })
                <input type="submit" value="Tak, usuń" class="btn btn-default" style="border:2px solid rgba(0,0,0,0.2)" />

            </div>

        }
    </div>

</div>

<hr style="height:1px; background-color:rgba(0,0,0,0.5);" />

E-Mechanik Web/Views/Services/Details.cshtml
@model E_Mechanik_Web.Models.Service

<div class="box-main">
    <div class="box-left" style="width:200px; margin-top:120px;">
        <div style="width:200px; height:200px; border:1px solid black; background-color:whitesmoke">
            <div style="width:180px; height:180px;margin-top:10px; margin-left:10px; border:1px solid black; background-color:white">
                <img src="@Url.Content(Model.mechanicProfile.ImagePatch)" style="width:160px; height:160px; margin-top:10px;" />
            </div>

        </div>


    </div>
    <div style="border-left:1px solid #d1d1d1;height:500px"></div>
    <div class="box-right" style="display:inline-block; text-align:left">

        <div style="border:1px solid black; padding:5px; background-color:rgb(255,255,255)">
            <div style="border:1px solid black; padding-left:10px; padding-bottom:50px; background-color:rgba(0,0,0,0.8); color:whitesmoke">

                <div style="margin-left:70px; margin-bottom:20px;">
                    <h1>@Model.mechanicProfile.CompanyName</h1>
                </div>
                <div class="customHr" style="margin-top:-15px; margin-bottom:20px; margin-right:130px; position:relative; "></div>
                <div style="margin-bottom:10px; font-size:17px;border-bottom:1px solid grey">
                    <b>Email:</b> <b>@Model.mechanicProfile.MechanicName</b>
                </div>

                <div style="margin-bottom:10px; font-size:15px;border-bottom:1px solid grey">
                    <b>Adres: </b>
                    <b>@Model.mechanicProfile.Address</b>
                </div>


                <div style="margin-bottom:10px; padding-left:53px; font-size:15px;border-bottom:1px solid grey">
                    <b>@Model.mechanicProfile.City</b>
                </div>
                <div style="margin-top:50px; margin-bottom:-30px; margin-left:100px;">
                    <button class="btn btn-default">@Html.ActionLink("Wyślij wiadomość", "DirectMessage", "Messages", new { to = Model.MechanicName } , null)</button>
                    <button class="btn btn-default">Oceń</button>
                </div>

            </div>
        </div>
    </div>
</div>
<p>
    <button class="btn btn-default">
        @Html.ActionLink("Lista serwisów", "GetServiceByName", "Services", new { name = Model.Name }, null)
    </button> 
  
</p>

E-Mechanik Web/Views/Services/Edit.cshtml
@model E_Mechanik_Web.Models.Service

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Service</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExecutionTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExecutionTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExecutionTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MechanicId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MechanicId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MechanicId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ServiceId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ServiceId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ServiceId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

E-Mechanik Web/Views/Services/GetServicesByName.cshtml
@model IEnumerable<E_Mechanik_Web.Models.Service>

<hr class="customHr" style="margin-bottom:30px; margin-top:50px;"/>

<div class="box-main" style="display:block; color:white; margin-left:auto; margin-right:auto; ">
    <div style="background-color:rgba(0,0,0,0.8);width:800px;line-height:50px; margin-left:150px; display:inline-block; border: 2px solid rgba(255, 255, 255, 0.6)">
        <div style="height:85%; width:95%; margin:auto; margin-top:8px; border: 1.5px solid rgba(0, 0, 0, 0.3)">

            <div style="margin-top:-20px; padding-top:10px; margin-bottom:-40px;">
                <div style="display:inline-block; margin-left:20px; text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width:736px;">
                    <h3 style="">Serwisy oferujące usługę:</h3>
                </div>
            </div>
            <hr />
            <div style="padding-left:40px;background-color:rgba(255,255,255,0.1); margin-top:-20px;"><b style="font-size:large; text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width:706px; ">@Model.FirstOrDefault().Name</b></div>
        </div>
    </div>




    @foreach (var service in Model)
    {



        <div style="background-color:rgba(0,0,0,0.8); height:100px; width:800px; margin-left:150px; display:block; border: 1px solid black">
            <div style="height:85%; width:95%; margin:auto; margin-top:8px; border: 1.5px solid rgba(0, 0, 0, 0.3)">

                <div style="margin-top:-20px; padding-top:10px; margin-bottom:-20px;">
                    <div style="display:inline-block; margin-left:20px;">
                        <h3 style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width:600px; cursor:pointer" onclick="location.href='Details/?id=@service.Id'">@service.mechanicProfile.CompanyName</h3>
                    </div>
                    <div style="display:inline-block; float:right; margin-right:20px; margin-top:20px;">
                        <div id="@service.MechanicName">
                            @Html.DisplayFor(modelItem => service.Distance) 
                        </div>
                    </div>
                </div>
                <hr />
                <div style="margin-top:-10px; padding-left:10px"><h5 style="text-overflow: ellipsis; white-space: nowrap; overflow: hidden; max-width:600px;"> @service.mechanicProfile.City,  @service.mechanicProfile.Address</h5></div>
            </div>
        </div>

        service.Distance = service.mechanicProfile.Address + ", " + service.mechanicProfile.City;

        if (Model.Count() > -1)
        {
            <script src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyBLMa7emvhGQMK0uYYrS-9aymoEhlX-4sU" type="text/javascript"></script>
            <script>
                                var source="X", destination;
                                var directionsDisplay;
                                var directionsService = new google.maps.DirectionsService();
                                // initialise the location of the map on Chichester in England (ref lat and lng)
                                var map = new google.maps.Map("", {
                                    center: { lat: 50.834697, lng: -0.773792 },
                                    zoom: 13,
                                    mapTypeId: 'roadmap'
                                });
                            document.getElementById(@Html.Raw(Json.Encode(@service.MechanicName))).innerHTML = "Obliczanie";

                                google.maps.event.addDomListener(window, 'load', function () {
                                    new google.maps.places.SearchBox(document.getElementById('lati'));
                                    new google.maps.places.SearchBox(@Html.Raw(Json.Encode(service.Distance)));
                                    directionsDisplay = new google.maps.DirectionsRenderer({ 'draggable': true });
                        });
                            setTimeout(function () {navigator.geolocation.getCurrentPosition(function (position) {

                            source =  position.coords.latitude + ", " + position.coords.longitude;
                                   destination = @Html.Raw(Json.Encode(service.Distance));

                                    //*********DISTANCE AND DURATION**********************//
                                    var service = new google.maps.DistanceMatrixService();
                                    service.getDistanceMatrix({
                                        origins: [source],
                                        destinations: [destination],
                                        travelMode: google.maps.TravelMode.DRIVING,
                                        unitSystem: google.maps.UnitSystem.METRIC,
                                        avoidHighways: false,
                                        avoidTolls: false
                                    }, function (response, status) {

                                        if (status == google.maps.DistanceMatrixStatus.OK && response.rows[0].elements[0].status != "ZERO_RESULTS" && response.rows[0].elements[0].status != "NOT_FOUND") {
                                            var distance = response.rows[0].elements[0].distance.text;
                                            document.getElementById(@Html.Raw(Json.Encode(@service.MechanicName))).innerHTML = distance;
                                            document.getElementById('e').innerHTML = "elo";
                                            //array[//MAŁPAHtml.Raw(Json.Encode(i))] = distance;
                                        } else {
                                             document.getElementById(@Html.Raw(Json.Encode(@service.MechanicName))).innerHTML = "Błędny adres";
                                        }
                                    });
                            });
                            }, 3000);





            </script>

        }


    }

</div>


    <hr class="customHr" style="margin-top:40px;" />
    <!---TODO - button powalający na sortowanie wyników-->

E-Mechanik Web/Views/Services/Index.cshtml
@model IEnumerable<E_Mechanik_Web.Models.Service>


<hr style="height:1px; background-color:rgba(0,0,0,0.5);" />
<div class="CustomHeader" style="height:90px">
    <h2>Dostępne usługi: </h2>
</div>

<div class="allServicesFromCategoryBox">

    @foreach (var item in Model)
    {
        <div class="singleServiceBox">
            @Html.ActionLink(@item.Name, "GetServicesByName", new { Controller = "Services", name = item.Name }, new { @class = "LinkColor" })

        </div>


    }

 </div>
<hr style="height:1px; background-color:rgba(0,0,0,0.5);" />

E-Mechanik Web/Views/Services/MyServices.cshtml
@model IEnumerable<E_Mechanik_Web.Models.Service>

<hr style="height:1px; background-color:rgba(0,0,0,0.5);" />
<div class="CustomHeader" style="height:90px">

    <h2>Twoje usługi:  <button style="float:right; margin-right:30px; width:50px; height:50px; margin-top:-10px; border-radius:50%; background-color:white; font-size:40px;">@Html.ActionLink("+", "Create", null, new { style = "text-decoration:none;" })</button></h2>

</div>

<div class="allServicesFromCategoryBox">


    @foreach (var item in Model)
    {
        <div class="singleServiceBox LinkColor" style="position:relative">
            @Html.DisplayFor(modelItem => item.Name)
            @Html.ActionLink("Usuń", "Delete", new { id = item.Id }, new { style = "float:right; margin-right:40px; color:whitesmoke;" })
        </div>
    }

</div>
<hr style="height:1px; background-color:rgba(0,0,0,0.5); margin-top:30px; position:relative" />